version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:latest
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: order_db  # This will create the initial DB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: docker.io/library/adminer:latest
    container_name: order-adminer
    restart: always
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
volumes:
  postgres_data:
